### ISSUE TITLE
tree-sitter injections support

### ISSUE THREAD

**Issue by kiryph** [TomLebeda/chroma_code#3]
I am trying to use the tree-sitter grammar https://github.com/gap-system/tree-sitter-gaptst which uses via injection https://github.com/gap-system/tree-sitter-gap:

```scm
([
  (comment)
  (gap_expression)
  ] @injection.content
 (#set! injection.language "gap"))

((input_line) @injection.content
 (#set! injection.language "gap")
 (#set! injection.combined))
```
https://github.com/gap-system/tree-sitter-gaptst/blob/60c76df4a0d82d8f47ec574525e703db7ed01579/queries/injections.scm

I could make the tree-sitter-gap work (i.e. without injection, see e.g. here https://github.com/leo-colisson/robust-externalize/discussions/48)

![346975119-01869744-23df-487f-9430-c68450d0ccbf](https://github.com/TomLebeda/chroma_code/assets/371756/da3bfb88-162c-4b90-bec4-b25ecbd1cf31)

However, when I do the same for `gaptst`, I do not get the highlighting for the injected part:

![Screenshot 2024-07-09 at 16 04 01](https://github.com/TomLebeda/chroma_code/assets/371756/1cd12b07-8612-4029-a0df-9ec880aa086e)

The result with the LaTeX package minted using pygments `gap-repl` looks like:

![Screenshot 2024-07-09 at 16 05 02](https://github.com/TomLebeda/chroma_code/assets/371756/d9b5fc12-a86d-4526-8122-31df63d7e650)

**Comment by TomLebeda** [comment]
Is the highlighting correct when you open the HTML produced just by treesitter itself? Chromacode just transforms that html into latex, the syntax parsing and highlighting is done fully by treesitter.

**Comment by kiryph** [comment]
> Is the highlighting correct when you open the HTML produced just by treesitter itself? 

The generated CLI output ~~HTML~~ is also incorrect:
![Screenshot 2024-07-09 at 16 31 48](https://github.com/TomLebeda/chroma_code/assets/371756/aadc9b38-ecf4-4457-b0a8-f442389ea033)

And here the generated HTML in Firefox:

![Screenshot 2024-07-09 at 16 45 28](https://github.com/TomLebeda/chroma_code/assets/371756/b832dc9e-f0b0-43de-816d-8ce407f91753)


The injection works in fenced code snippets in markdown files in Neovim:

![Screenshot 2024-07-09 at 16 31 16](https://github.com/TomLebeda/chroma_code/assets/371756/ff89b5fb-a93d-4eb1-8fdc-745ab8e091f3)

and also in tst files. Here a screenshot of neovim v0.10 with the QueryEditor visible

![Screenshot 2024-07-09 at 17 20 53](https://github.com/TomLebeda/chroma_code/assets/371756/9b1390aa-5263-4e53-9d6d-5e85b6d33c71)


This sounds like that it is not an issue of chroma_code, but a general tree sitter configuration issue.

Any help/pointer would still be appreciated

**Comment by kiryph** [comment]
I could fix it with following change in `package.json` of `tree-sitter-gaptst`:

```diff
diff --git a/package.json b/package.json
index 042c227..297960e 100644
--- a/package.json
+++ b/package.json
@@ -59,6 +59,7 @@
       "file-types": [
         "tst"
       ],
+      "injection-regex": "^gaptst$",
       "highlights": [
         "queries/highlights.scm"
       ],
```

![Screenshot 2024-07-09 at 18 19 42](https://github.com/TomLebeda/chroma_code/assets/371756/fd5349f3-5ab5-484d-a117-7a74f47ad10a)

I looked at the output of `tree-sitter dump-languages` for tree-sitter-markdown
```sh
❯ tree-sitter dump-languages
scope: text.markdown
parser: "/Users/kiryph/Repositories/treesitter-grammars/tree-sitter-markdown/tree-sitter-markdown"
highlights: Some(["tree-sitter-markdown/queries/highlights.scm"])
file_types: ["md"]
content_regex: None
injection_regex: Some(Regex("^(markdown|md)$"))
```

**Comment by TomLebeda** [comment]
I see, so the issue was in the configuration of tree-sitter. Unfortunately I don't have any significant experience with tree-sitter's injections, so the best I could do is point you toward the [official guide](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection). 

So if I understand you last comment correctly, you figured it out?

**Comment by kiryph** [comment]
> So if I understand you last comment correctly, you figured it out?

Yes, I figured it out. I think the official documentation is not very good. I could only figure it out by comparing to other grammars with injections:

**Comment by TomLebeda** [comment]
Awesome!
Yes, the official docs are a bit sparse, I also had issues to understand it when I was starting this project.
